### ISSUE TITLE
Maintenance of the protobuf-embedded-c project

### ISSUE THREAD

**Issue by berezovskyi** [berezovskyi/protobuf-embedded-c#56]
I think we need to determine if there are any plans to maintain this project in the future. This issue is mainly directed at @nvpopa as he is the only contributor identifed by github to have an account here.

Vlad, as I understand, the project was developed as part of the E-Energy-Grid demonstrator. Do you still work in the embedded industry?

My interest in this library (or [Nanopb](https://github.com/nanopb/nanopb)) is due to my need to have some protocol between a data gathering microcontroller and an embeded system used to process (and store that data).

I plan to evaluate both projects and direct my efforts at one that suits me best.

I know that some may hate me for this but I am CCing everybody who have cloned this repo on github before with 2 questions:
- have you used this library at all?
- do you still have a use case for it that motivated you to fork this project?

---

CC @mikevoyt, @simonAndre, @benmargolin, @AlexanderSkvortsov, @bumpy-b, @locomuco, @RohanBenkar, @ctiller, @bitmorse, @yossi-k

**Comment by yossi-k** [comment]
I forked this library because I was evaluating it for a use-case similar to
yours.

I haven't got the chance to use it yet, and quite frankly I don't think I
ever will.

**Comment by berezovskyi** [comment]
@yossi-k thanks for a prompt reply. Feel free to unsubscribe from the notifications if you don't have any interest in this project any longer.

**Comment by mikevoyt** [comment]
We used it at my previous company on a prototype we were developing.  It worked fined, but I left a few months ago, and I believe they switched to a different protobuf implementation since.

**Comment by berezovskyi** [comment]
@mikevoyt Thanks Mike, do you happen to know if that implementation was Nanopb?

**Comment by mikevoyt** [comment]
Not sure what they moved to, sorry...

-mike

**Comment by abhilashdeshmukh** [comment]
@berezovskyi 
Hi, I just started working on this, so while trying to build the project in eclipse I am facing some issue. Can you help me with it?

Error:

eclipse can not resolve class such as ProtoLexer, ProtoParser etc.
 
Can you suggest me what could have gone wrong in my setup? I know it is very less information, so let me know if you want any further information.

Thank you

**Comment by berezovskyi** [comment]
@abhilashdeshmukh hi, sounds like you have some ANTLR problems. I do not have much time to debug this now, but seems like there are extra ANTRL requirements: https://github.com/berezovskyi/protobuf-embedded-c#development-environment

**Comment by berezovskyi** [comment]
Will be closing the repo
